modLoader = "javafml"
loaderVersion = "${fml_requirements}"
license = "MIT"
issueTrackerURL="https://github.com/LimonBlaze/origins-accessibilities/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Origins: Accessibilities"
displayURL="https://github.com/LimonBlaze/origins-accessibilities/"
logoFile="pack.png"
authors="LimonBlaze"
description = "An add-on for the Origins mod making your Origins life easier."

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${mc_requirements}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_requirements}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "origins"
mandatory = true
versionRange = "${origins_requirements}"
ordering = "NONE"
side = "BOTH"
