name: Release
on: [workflow_dispatch]

permissions:
  contents: write

env:
  MINECRAFT_VERSION: 1.16.5
  JAVA_VERSION: 8
  VERSION: 0.9991

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 8

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          # Modrinth
          modrinth-id: O5i3hY4L
          modrinth-featured: true
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # CurseForge
          curseforge-id: 664597
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # Config
          name: "Origins: Accessibilities ${{ env.VERSION }} for ${{ env.MINECRAFT_VERSION }}"
          version: ${{ env.VERSION }}
          version-type: release
          changelog-file: changelog/${{ env.VERSION }}.md
          files-primary: build/libs/*-${{ env.VERSION }}!(-@(dev|sources|slim)).jar
          files-secondary: ""

          loaders: |
            forge
          game-versions: |
            ${{ env.MINECRAFT_VERSION }}
          java: |
            ${{ env.JAVA_VERSION }}
          retry-attempts: 2
          retry-delay: 10000
